const FETCH_GOALS_REQUEST = 'mg/goals/FETCH_GOALS_REQUEST'
const FETCH_GOALS_SUCCESS = 'mg/goals/FETCH_GOALS_SUCCESS'
const FETCH_GOALS_FAILURE = 'mg/goals/FETCH_GOALS_FAILURE'

export default {
  FETCH_GOALS_REQUEST,
  FETCH_GOALS_SUCCESS,
  FETCH_GOALS_FAILURE
}
