const FETCH_GOALS_REQUEST = 'mg/goals/FETCH_GOALS_REQUEST'
const FETCH_GOALS_SUCCESS = 'mg/goals/FETCH_GOALS_SUCCESS'
const FETCH_GOALS_FAILURE = 'mg/goals/FETCH_GOALS_FAILURE'

const SUBMIT_GOALS_REQUEST = 'mg/goals/SUBMIT_GOALS_REQUEST'
const SUBMIT_GOALS_SUCCESS = 'mg/goals/SUBMIT_GOALS_SUCCESS'
const SUBMIT_GOALS_FAILURE = 'mg/goals/SUBMIT_GOALS_FAILURE'

export default {
  FETCH_GOALS_REQUEST,
  FETCH_GOALS_SUCCESS,
  FETCH_GOALS_FAILURE,
  SUBMIT_GOALS_REQUEST,
  SUBMIT_GOALS_SUCCESS,
  SUBMIT_GOALS_FAILURE
}
