const FETCH_TASKS_REQUEST = 'ss/tasks/FETCH_TASKS_REQUEST'
const FETCH_TASKS_SUCCESS = 'ss/tasks/FETCH_TASKS_SUCCESS'
const FETCH_TASKS_FAILURE = 'ss/tasks/FETCH_TASKS_FAILURE'

const SUBMIT_TASKS_REQUEST = 'ss/tasks/SUBMIT_TASKS_REQUEST'
const SUBMIT_TASKS_SUCCESS = 'ss/tasks/SUBMIT_TASKS_SUCCESS'
const SUBMIT_TASKS_FAILURE = 'ss/tasks/SUBMIT_TASKS_FAILURE'

const EDIT_TEXT_TASKS_REQUEST = 'ss/tasks/EDIT_TEXT_TASKS_REQUEST'
const EDIT_TEXT_TASKS_SUCCESS = 'ss/tasks/EDIT_TEXT_TASKS_SUCCESS'
const EDIT_TEXT_TASKS_FAILURE = 'ss/tasks/EDIT_TEXT_TASKS_FAILURE'

export default {
  EDIT_TEXT_TASKS_REQUEST,
  EDIT_TEXT_TASKS_SUCCESS,
  EDIT_TEXT_TASKS_FAILURE,
  FETCH_TASKS_REQUEST,
  FETCH_TASKS_SUCCESS,
  FETCH_TASKS_FAILURE,
  SUBMIT_TASKS_REQUEST,
  SUBMIT_TASKS_SUCCESS,
  SUBMIT_TASKS_FAILURE
}
