const FETCH_TASKS_REQUEST = 'mg/tasks/FETCH_TASKS_REQUEST'
const FETCH_TASKS_SUCCESS = 'mg/tasks/FETCH_TASKS_SUCCESS'
const FETCH_TASKS_FAILURE = 'mg/tasks/FETCH_TASKS_FAILURE'

const SUBMIT_TASKS_REQUEST = 'mg/tasks/SUBMIT_TASKS_REQUEST'
const SUBMIT_TASKS_SUCCESS = 'mg/tasks/SUBMIT_TASKS_SUCCESS'
const SUBMIT_TASKS_FAILURE = 'mg/tasks/SUBMIT_TASKS_FAILURE'

export default {
  FETCH_TASKS_REQUEST,
  FETCH_TASKS_SUCCESS,
  FETCH_TASKS_FAILURE,
  SUBMIT_TASKS_REQUEST,
  SUBMIT_TASKS_SUCCESS,
  SUBMIT_TASKS_FAILURE
}
