const FETCH_TASKS_REQUEST = 'mg/goals/FETCH_TASKS_REQUEST'
const FETCH_TASKS_SUCCESS = 'mg/goals/FETCH_TASKS_SUCCESS'
const FETCH_TASKS_FAILURE = 'mg/goals/FETCH_TASKS_FAILURE'

export default {
  FETCH_TASKS_REQUEST,
  FETCH_TASKS_SUCCESS,
  FETCH_TASKS_FAILURE
}
