const FETCH_GOALS_REQUEST = 'ss/goals/FETCH_GOALS_REQUEST'
const FETCH_GOALS_SUCCESS = 'ss/goals/FETCH_GOALS_SUCCESS'
const FETCH_GOALS_FAILURE = 'ss/goals/FETCH_GOALS_FAILURE'

const SUBMIT_GOALS_REQUEST = 'ss/goals/SUBMIT_GOALS_REQUEST'
const SUBMIT_GOALS_SUCCESS = 'ss/goals/SUBMIT_GOALS_SUCCESS'
const SUBMIT_GOALS_FAILURE = 'ss/goals/SUBMIT_GOALS_FAILURE'

const UPDATE_STATUS_REQUEST = 'ss/goals/UPDATE_STATUS_REQUEST'
const UPDATE_STATUS_SUCCESS = 'ss/goals/UPDATE_STATUS_SUCCESS'
const UPDATE_STATUS_FAILURE = 'ss/goals/UPDATE_STATUS_FAILURE'

export default {
  FETCH_GOALS_REQUEST,
  FETCH_GOALS_SUCCESS,
  FETCH_GOALS_FAILURE,
  SUBMIT_GOALS_REQUEST,
  SUBMIT_GOALS_SUCCESS,
  SUBMIT_GOALS_FAILURE,
  UPDATE_STATUS_REQUEST,
  UPDATE_STATUS_SUCCESS,
  UPDATE_STATUS_FAILURE
}
